const staticServices = [
  { num: "01", tag: "VIDEO CREATIVE", title: "Video Editing", description: "High-impact video editing for reels, commercials, YouTube, social content and promotional campaigns.", priceAmount: "₹599", priceSuffix: "/ STARTING FROM", priceLabel: "PRICING", priceValue: "Starting from ₹599+", btnText: "BOOK THIS SERVICE →", btnLink: "#book", isCustom: false },
  { num: "02", tag: "IMAGE DESIGN", title: "Photo Editing", description: "Professional retouching, color grading, thumbnail creation and visual enhancement for individuals and brands.", priceAmount: "₹299", priceSuffix: "/ STARTING FROM", priceLabel: "PRICING", priceValue: "Starting from ₹299+", btnText: "BOOK THIS SERVICE →", btnLink: "#book", isCustom: false },
  { num: "03", tag: "ON-LOCATION", title: "Indoor & Outdoor Shooting", description: "On-site video and photo coverage for events, brand shoots, personal sessions and creative projects.", priceAmount: "₹4,000", priceSuffix: "/ STARTING FROM", priceLabel: "PRICING", priceValue: "Starting from ₹4,000+", btnText: "BOOK THIS SERVICE →", btnLink: "#book", isCustom: false },
  { num: "04", tag: "WEB DEVELOPMENT", title: "Website Design", description: "Clean, responsive, high-performance website design and development tailored to showcase your business or personal brand.", priceAmount: "₹3,999", priceSuffix: "/ STARTING FROM", priceLabel: "PRICING", priceValue: "Starting from ₹3,999+", btnText: "BOOK THIS SERVICE →", btnLink: "#book", isCustom: false },
  { num: "05", tag: "DIGITAL SKILLS", title: "Computer Classes", description: "Practical computer learning covering essential digital skills, software basics and everyday computer usage.", priceAmount: "₹3,000", priceSuffix: "/ STARTING FROM", priceLabel: "PRICING", priceValue: "Starting from ₹3,000+", btnText: "START LEARNING →", btnLink: "#book", isCustom: false },
  { num: "06", tag: "CREATIVE LEARNING", title: "Piano Classes", description: "Structured, beginner-friendly to intermediate piano instruction covering fundamentals, music reading and practical practice.", priceAmount: "₹3,000", priceSuffix: "/ PER MONTH", priceLabel: "PRICING", priceValue: "₹3,000 per month", btnText: "START LEARNING →", btnLink: "#book", isCustom: false },
  { num: "07", tag: "CUSTOM SOLUTION", title: "Custom Requirement", description: "Have a project that falls outside the listed services? Tell us what you need and let's build the right solution together.", priceAmount: "Let's Discuss", priceSuffix: "", priceLabel: "PRICING", priceValue: "Let's Discuss", btnText: "CONNECT ON WHATSAPP →", btnLink: "https://wa.me/916304834605?text=Hi%20Pulse_Blend_Media%2C%20I%20have%20a%20custom%20requirement%20and%20would%20like%20to%20discuss%20my%20project.", isCustom: true }
];

module.exports = {
  findAll: async () => staticServices,
  findByTitle: async (title) => staticServices.find(s => s.title.toLowerCase() === title.toLowerCase()) || null
};
